import Head from 'next/head'

export default function About() {
  return (
    <div className="redirect">
      <Head>
        <title>About Tummy Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>About Tummy Hub</h1>
        <p>Tummy Hub is a pretend website built for my final <a href="https://xpro.mit.edu/programs/program-v1:xPRO+PCCx+R1/">MITxPro bootcamp project</a>. The starter code was provided to me by the program, and is based on <a href="https://strapi.io/blog/nextjs-react-hooks-strapi-food-app-1">Ryan Belke's Deliveroo tutorial</a> for Strapi version 3. This tutorial was helpful to me in understanding using Next JS with Strapi overall, but especially in implementing the site's authorization.

        In addition to heavily utilizing the official documentation and help resources for the many tools and products used in this web application, I found these resources helpful:<br/><br/>

        <ul>
          <li><a href="https://www.purereact.com/">Pure React by David Cedea</a> helped me understand context and useEffect.</li>

          <li>The "Watch and Learn" YouTube channel's <a href="https://www.youtube.com/watch?v=RDcW_0iB5UE">Making Websites With Next.js And Strapi - [06] - Dynamic Routes</a> video helped me set up my own dynamic restaurant routes and pages.</li>

          <li>The "Learning on the Job" YouTube channel's <a href="https://www.youtube.com/watch?v=NnOng-on7cQ">Changing Default Strapi Media Uploader to Cloudinary</a> showed me how to implement Cloudinary after deploying my backend to Heroku. I could not make the Heroku documentation work, and am so grateful for this video! </li>

          <li>GOKUL A C for the really clear and concise article about <a href="https://medium.com/featurepreneur/how-to-connect-github-to-heroku-be6ff27419d3">deploying from GitHub to Heroku</a>. I was really strugging with the terminal and working with the browser made it easier for me to work through my error logs.</li>

          <li>Jay Clark in the April Cohort for her many encouragements to all of us in the June cohort and specifically for suggesting that we check which version of Node we were using to deploy. Thank you!</li>
        </ul>
    
        The food allergy filter was inspired by my life as the parent of a child with a food allergy. I am so grateful to the restaurant owners and workers who have always taken the time to help my family identify which dishes my child can safely eat. Exploring Chicago's many delicious restaurants is one of our favorite family activities. I tried to make the copy on my site pretty generic, but I want to acknowledge that most of the dishes and all of the restaurants were were inspired by real restaurants and their menus. Check them out next time you're in Chicago!<br/><br/>

        <ul>
          <li><a href="https://www.ethiopiandiamondrestaurants.com/home">Ethiopian Diamond</a></li>
          <li><a href="https://www.dakwings.com/">Dak Wings</a></li>
          <li><a href="http://www.indiecafe.us/menu.html">Indie Cafe</a></li>
          <li><a href="https://www.lulacafe.com/">Lula Cafe</a></li>
          <li><a href="https://www.dollopcoffee.com/locations/diner-location/">Dollop Diner</a></li>
          <li><a href="https://www.ladygregorys.com/">Lady Gregory's</a></li>
        </ul>

        All photos are from <a href='https://www.pexels.com/'>Pexels</a>. I have left the orginal file names intact, so you can see the photographer's name. I'm very grateful to these photographers for making their work available royalty free to developers like me.<br/><br/>
        
        Access Tummy Hub's <a href='https://documenter.getpostman.com/view/18869430/Uyr5oeo6'>API documentation here</a>.</p>
        <style jsx>
          {`
            a, Link {
              color: blue;
              text-decoration: underline;
            }
            a:link {
              text-decoration: underline;
              color: blue;
            }
          `}
        </style>
      </main>
    </div>
  )
}
