import Head from 'next/head'

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="redirect">
        <h1> Get in Touch
        </h1>
        <p>Your feedback matters! Let me know your thoughts. Please email me at YOUR EMAIL HERE.</p>
      </main>
    </div>
  )
}
